### ISSUE TITLE
Add dependabot to repos using NPM, GH actions

### ISSUE THREAD

**Issue by dearshrewdwit** [boolean-uk/software-developer#176]
- [ ] [JS Fundamentals](https://www.notion.so/boolean/cf71e104602440a2b22ea756e7c7e6e3?v=1e925ad0c4874290811a1f1a8bee0783&p=fb619edf34ae49de9c6ea43b0c92d7b9&pm=s)
- [ ] [React](https://www.notion.so/boolean/cf71e104602440a2b22ea756e7c7e6e3?v=1e925ad0c4874290811a1f1a8bee0783&p=08b3c299e16f48409703a935363a62e2&pm=s)
- [ ] [Building APIs](https://www.notion.so/boolean/cf71e104602440a2b22ea756e7c7e6e3?v=1e925ad0c4874290811a1f1a8bee0783&p=eb8dfb6016344271927ac65fdfd7afa8&pm=s)
- [ ] [Database](https://www.notion.so/boolean/cf71e104602440a2b22ea756e7c7e6e3?v=1e925ad0c4874290811a1f1a8bee0783&p=c4977a724fe143bcacb46acef526dc0e&pm=s)
- [ ] [Auth](https://www.notion.so/boolean/cf71e104602440a2b22ea756e7c7e6e3?v=1e925ad0c4874290811a1f1a8bee0783&p=cef3751bb44f4ce49a4120813017cad6&pm=s)

**Comment by dearshrewdwit** [comment]
**Step 1**
Add Dependabot to a repo: click on repo settings and code security & analysis

**Step 2**
Configure Dependabot
1. enable Dependabot version updates
![](https://cdn.discordapp.com/attachments/813727076699209759/1063472701399912519/Screenshot_2023-01-13_at_14.56.51.png)
![](https://cdn.discordapp.com/attachments/813727076699209759/1063472701873860628/Screenshot_2023-01-13_at_14.56.58.png)
2.  replace the file contents with the below

```yml
version: 2
updates:
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    # Workflow files stored in the
    # default location of `.github/workflows`
    directory: "/"
    schedule:
      interval: "weekly"
```
3.  commit the change
