### ISSUE TITLE
Configure Github Actions to run the NUnit tests on PR

### ISSUE THREAD

**Issue by Logi13** [boolean-uk/software-developer#194]

**Comment by Logi13** [comment]
This will run the NUnit Tests. Might be worth it to point to standard criteria only, running a specific test file
```
name: Standard Criteria

on:
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      # 1) Check out the source code so that the workflow can access it.
      - uses: actions/checkout@v2
      # 2) Set up the .NET CLI environment for the workflow to use.
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'
      # 3) Restore the dependencies and tools of a project or solution.
      - name: Install dependencies
        run: dotnet restore
      # 4) Build a project or solution and all of its dependencies.
      - name: Build
        run: dotnet build --configuration Release
      # 5) Install NUnit console.Runner so we can run the tests from the console
      #- name: Install NUnit.ConsoleRunner
      #  run: nuget install NUnit.ConsoleRunner -Version 3.13.0 -DirectDownload -OutputDirectory .   
      # 6) Test a project or solution.
      #- name: Run UnitTests
      #  run: ./NUnit.ConsoleRunner.3.13.0/tools/nunit3-console.exe  path/to/test.dll
      - name: Run NUnit tests
        run: dotnet test --no-build --verbosity normal --filter "TestCategory!=Integration"
```
